version: "3.9"
services:
  db:
    build: .
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "ASSET-manager12345!"
      MSSQL_DB: "asset-manager"
      ACCEPT_EULA: "Y"
      MSSQL_USER: "ASSET_MANAGER"
      MSSQL_PASSWORD: "admin123!"
    ports:
      - "1433:1433"
    container_name: mssqldev
  mailServer:
    image: djfarrelly/maildev
    command: home/node/bin/maildev --web 8082 --smtp 10025
    ports:
      - "8082:8082"
      - "10025:10025"