spring:
  datasource:
    url: jdbc:sqlserver://localhost;database=asset-manager
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: ASSET-manager12345!
  mail:
    host: localhost
    port: 10025

ad.domain: assetManager.local
ad.url: ldap://192.168.56.101:389

mail:
  sender: asset-manager@dhl.com

frontend:
  url: 'http://localhost:3000'

